"""add 3 vectors logic

Revision ID: 158e3ad7612e
Revises: 7fc1527d0fa3
Create Date: 2025-08-28 20:15:10.850872

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '158e3ad7612e'
down_revision = '7fc1527d0fa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_vectors', sa.Column('ocr_content', sa.Text(), nullable=True))
    op.add_column('game_vectors', sa.Column('ocr_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('game_vectors', sa.Column('description_content', sa.Text(), nullable=True))
    op.add_column('game_vectors', sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('game_vectors', sa.Column('labels_content', sa.Text(), nullable=True))
    op.drop_column('game_vectors', 'vector_embedding')
    op.drop_column('game_vectors', 'extracted_text')
    op.drop_column('game_vectors', 'labels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_vectors', sa.Column('labels', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('game_vectors', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('game_vectors', sa.Column('vector_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False))
    op.drop_column('game_vectors', 'labels_content')
    op.drop_column('game_vectors', 'description_embedding')
    op.drop_column('game_vectors', 'description_content')
    op.drop_column('game_vectors', 'ocr_embedding')
    op.drop_column('game_vectors', 'ocr_content')
    # ### end Alembic commands ###