"""create users table

Revision ID: b5ca817a792b
Revises: 50887aed5daa
Create Date: 2025-09-01 15:03:11.548546

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = 'b5ca817a792b'
down_revision = '50887aed5daa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_credits', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('users', 'credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'token_credits')
    # ### end Alembic commands ###