"""added game avatar

Revision ID: 9fc3e544fa6e
Revises: ef15942a8a37
Create Date: 2025-09-04 14:32:34.093663

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '9fc3e544fa6e'
down_revision = 'ef15942a8a37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('avatar', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'avatar')
    # ### end Alembic commands ###