"""update games logic

Revision ID: 6860d30d6ab5
Revises: 522968d3d68a
Create Date: 2025-08-21 16:55:01.655692

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '6860d30d6ab5'
down_revision = '522968d3d68a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('games', sa.Column('series_id', sa.UUID(), nullable=True))
    op.add_column('games', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'games', 'game_series', ['series_id'], ['id'])
    op.drop_column('games', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'created_by')
    op.drop_column('games', 'series_id')
    op.drop_column('games', 'title')
    # ### end Alembic commands ###