"""create users table

Revision ID: 1696ab204854
Revises: e59043bcfc44
Create Date: 2025-08-27 09:48:42.417187

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '1696ab204854'
down_revision = 'e59043bcfc44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DO $$\n                          BEGIN\n                              IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'imageprocessingstatus') THEN\n                                  CREATE TYPE imageprocessingstatus AS ENUM ('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRYING');\n                              END IF;\n                          END $$;")
    op.add_column('game_images', sa.Column('blob_url', sa.String(length=1000), nullable=False))
    op.add_column('game_images', sa.Column('processing_status', sa.Enum('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRYING', name='imageprocessingstatus'), nullable=False))
    op.add_column('game_images', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('game_images', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('game_images', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('game_images', sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_images', 'processing_completed_at')
    op.drop_column('game_images', 'processing_started_at')
    op.drop_column('game_images', 'retry_count')
    op.drop_column('game_images', 'processing_error')
    op.drop_column('game_images', 'processing_status')
    op.drop_column('game_images', 'blob_url')
    # ### end Alembic commands ###