"""create users table

Revision ID: 10ac6c04f690
Revises: 6860d30d6ab5
Create Date: 2025-08-22 10:54:11.165751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ac6c04f690'
down_revision = '6860d30d6ab5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###