"""added game avatar

Revision ID: 91859bf23f8f
Revises: 9fc3e544fa6e
Create Date: 2025-09-04 14:47:19.712323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91859bf23f8f'
down_revision = '9fc3e544fa6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###