"""add labels to vectors

Revision ID: 7fc1527d0fa3
Revises: 01eb4dd9459c
Create Date: 2025-08-28 19:40:26.430182

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '7fc1527d0fa3'
down_revision = '01eb4dd9459c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_vectors', sa.Column('labels', sa.Text(), nullable=True))
    op.add_column('game_vectors', sa.Column('labels_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_vectors', 'labels_embedding')
    op.drop_column('game_vectors', 'labels')
    # ### end Alembic commands ###