"""ad search_method

Revision ID: 1f39ed494b9c
Revises: 158e3ad7612e
Create Date: 2025-08-29 00:19:21.883155

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '1f39ed494b9c'
down_revision = '158e3ad7612e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('search_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'search_method')
    # ### end Alembic commands ###