"""add image batch system

Revision ID: 97764c25fb40
Revises: 1696ab204854
Create Date: 2025-08-27 18:57:06.263292

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '97764c25fb40'
down_revision = '1696ab204854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('total_images', sa.Integer(), nullable=False),
    sa.Column('processed_images', sa.Integer(), nullable=False),
    sa.Column('failed_images', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRYING', 'PARTIALLY_COMPLETED', name='batchstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game_images', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'game_images', 'image_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_images', type_='foreignkey')
    op.drop_column('game_images', 'batch_id')
    op.drop_table('image_batches')
    # ### end Alembic commands ###